### ISSUE TITLE
save the default on camera and mic choice

### ISSUE THREAD

**Issue by dbish** [AugmendTech/issues-and-feedback#2]
if you have multiple cameras and mics, we should not forget which one you chose last time every time you reopen augmend

**Comment by TimMisiak** [comment]
I've made two changes here that will make it into our next release:

1. Camera and mic are saved immediately when saved, even if you don't start recording.
2. Preferences are saved to a local preference file instead of relying on the localStorage API, which will make preference saving more consistent.
